services:
  server:
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ${LOCAL_DRIVE_STATIC_DIR}
        target: /app/static
    profiles:
      - disabled

  server-dev:
    extends: server
    build:
      context: .
      target: dev
    volumes:
      - type: bind
        source: ./src
        target: /app/src
    profiles:
      - dev

  server-prod:
    extends: server
    build:
      context: .
      target: prod
    profiles:
      - prod
